# fly.toml app configuration file generated for flightkit-builder on 2024-08-17T10:38:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flightkit'
primary_region = 'ewr'

[build]
dockerfile = 'Dockerfile'
